/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : get-printer-dpi
 #	author : miyako
 #	2016/03/07
 #
 # --------------------------------------------------------------------------------*/



// --- get-printer-dpi
void PRINTER_DPI_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void GET_PRINTER_DPI(sLONG_PTR *pResult, PackagePtr pParams);
